apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swe-agent

resources:
  - ../../base
  - external-secrets.yaml

patches:
  - target:
      kind: ConfigMap
      name: swe-agent-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: "production"
      - op: replace
        path: /data/LOG_LEVEL
        value: "INFO"
